/*jshint esversion: 6 */

const advantagesDisadvantagesOptions = [
    { "text": "Пусто", "disabled": false, "selected": true },
    { "text": "Достоинства", "disabled": true, "selected": false },
    { "text": "\u00A0Физические", "disabled": true, "selected": false },
    { "text": "\u00A0\u00A0Обострённые чувства (-1 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Амибекстер (-1 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Внушительный тип (-1 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Кошачье равновесие (-1 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Жаворонок (-1 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Поглощение пищи (-1 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Знакомое лицо (-1 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Пышущий здоровьем (-2 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Чарующий голос (-2 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Сорвиголова (-3 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Эффективное усвоение (-3 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Огромный размер (-4 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0Умственные", "disabled": true, "selected": false },
    { "text": "\u00A0\u00A0Холодная логика (-1 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Здравый смысл (-1 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Концентрация (-1 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Самоанализ (-1 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Язык (-1 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Чувство времени (-1 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Полезные знания (-1 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Кодекс чести (-2 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Компьютерная одарённость (-2 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Холодная логика (-2 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Эйдетическая память (-2 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Полиглот (-2 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Холодное сердце (-3 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Железная воля (-3 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Развитый не по годам (-3 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0Социальные", "disabled": true, "selected": false },
    { "text": "\u00A0\u00A0Завсегдатай Элизиума (-1 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Бывший гуль (-1 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Безвредный (-1 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Прирожденный лидер (-1 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Прославленный сир (-1 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Протеже (-1 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Знаменитость (-1 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Столкнувшийся с Шабашем (-1 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Долг (-(1/6) pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Громила (-2 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Старый друг (-2 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Друг \"хранителя закона\" (-2 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Свободная дорога (-2 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Святость (-2 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Знаток врагов (-2 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Знаток других (-2 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Друг подземелий (-3 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Крот (-3 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Восходящая звезда (-3 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Порванные Узы (-4 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Дружба клана (-4 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Дружба с Примогенами\\Епископами (-4 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0Сверхъестественные", "disabled": true, "selected": false },
    { "text": "\u00A0\u00A0Дезориентирующая аура (-1 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Исцеляющее касание (-1 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Безобидность для животных (-1 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Медиум (-2 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Магическая сопротивляемость (-2 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Сокрытое диаблери (-3 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Удачливость (-3 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Способности предсказателя (-3 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Дух-наставник (-3 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Истинная любовь (-4 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Дополнительная дисциплина (-5 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Иммунитет к узам (-5 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Девять жизней (-6 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Истинная вера (-7 pt)", "disabled": false, "selected": false },
    { "text": "Недостатки", "disabled": true, "selected": false },
    { "text": "\u00A0Физические", "disabled": true, "selected": false },
    { "text": "\u00A0\u00A0Тугоухость (+1 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Коротышка (+1 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Запах могилы (+1 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Тик/Судороги (+1 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Плохое зрение (+1 или +3 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Четырнадцатое поколение (+2 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Уродство (+2 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Слабый укус (+2 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Заразный укус (+2 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Одноглазый (+2 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Уязвимость к серебру (+2 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Открытая рана (+2 или +4 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Пристрастие (+3 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Ребенок (+3 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Дефект (+3 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Светящиеся глаза (+3 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Хромота (+3 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Лентяй (+3 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Чудовищная внешность (+3 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Торчащие клыки (+3 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Постоянная рана (+3 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Медленное лечение (+3 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Пятнадцатое поколение (+4 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Разносчик болезней (+4 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Глухота (+4 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Немота (+4 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Слабая кровь (+4 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Мертвая плоть (+5 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Бесплодное витэ (+5 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Слепота (+6 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0Умственные", "disabled": true, "selected": false },
    { "text": "\u00A0\u00A0Глубокий сон (+1 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Нетерпеливый (+1 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Кошмары (+1 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Разборчивость в добыче (+1 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Робость (+1 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Мягкосердечие (+1 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Нарушение речи (+1 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Неуверенность (+1 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Амнезия (+2 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Лунатизм (+2 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Фобия (+2 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Вспыльчивость (+2 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Стереотипность (+2 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Территориальность (+2 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Жажда невинности (+2 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Мстительность (+2 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Жертва Маскарада (+2 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Слабовольный (+3 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Полное потребление (+4 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Комплекс вины (+4 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Воспоминания (+6 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0Социальные", "disabled": true, "selected": false },
    { "text": "\u00A0\u00A0Проваленное представление (+1 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Тёмная тайна (+1 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Бесполезный (+1 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Недопонимание (+1 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Бесславный сир (+1 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Ошибочное опознание (+1 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Вновь прибывший (+1 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Новое дитя (+1 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Цель вербовки (+1 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Негодование сира (+1 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Особая ответственность (+1 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Симпатии (+1 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Враг (+(1/5) pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Узы (+2 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Орудие в чужих руках (+2 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Улизнувшая цель (+2 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Неудача (+2 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Нарушитель Маскарада (+2 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Старые времена (+2 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Конкурирующий сир (+2 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Нахальство (+2 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Бесчестье крови (+3 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Бывший князь (+3 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Жертва преследования (+3 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Стукач (+3 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0В постели с врагом (+3 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Преследование (+4 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Враждебность клана (+4 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Мерзкий регнант (+4 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Перенапряжение (+4 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0На испытательном сроке (+4 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Кровавая охота (+4 или +6 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Посмешище (+5 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Красный список (+7 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0Сверхъестественные", "disabled": true, "selected": false },
    { "text": "\u00A0\u00A0Отсутствие отражения (+1 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Холодный ветер (+1 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Восприимчивость к чесноку (+1 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Прикосновение холода (+1 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Проклятый (+(1/5) pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Маяк нечестивости (+2 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Взгляд мертвеца (+2 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Зловещее присутствие (+2 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Повелитель мух (+2 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Невозмож. пере-кать тек. воду (+3 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Преследование духом (+3 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Восприимчивость к крестам (+3 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Хватка проклятого (+4 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Злой рок (+5 pt)", "disabled": false, "selected": false },
    { "text": "\u00A0\u00A0Чувствительность к свету (+5 pt)", "disabled": false, "selected": false }
];